# This is the master file for gitlab services
# See docker-compose reference :

version:  '2'

services:

  gitlab:
    image: gitlab:${GITLAB_VERSION}
    build:
      context: ./gitlab
      dockerfile: Dockerfile
      args:
        - GITLAB_VERSION=${GITLAB_VERSION}
        - GITLAB_DIR=${GITLAB_VOLUME}/${GITLAB_VERSION}
        - GITLAB_VOLUME=${GITLAB_VOLUME}
    restart: always
    container_name: gitlab
    ports:
      - '587:587'
      - '443:443'
      - '80:80'
      - '4567:4567'
      - '2222:22'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = '${SMTP_SERVER_DOMAIN}'
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_authentication'] = 'plain'
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_user_name'] = '${SMTP_USERNAME}'
        gitlab_rails['smtp_password'] = '${SMTP_PASSWORD}'
        gitlab_rails['smtp_domain'] = '$SMTP_DOMAIN'
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['registry_path'] = '${GITLAB_VOLUME}/registry'


        external_url 'https://${GITLAB_DOMAIN}'
        registry_external_url 'https://${GITLAB_REGISTRY_DOMAIN}:4567'
        letsencrypt['enable'] = true
        letsencrypt['contact_emails'] = ['${SMTP_USERNAME}']
        letsencrypt['auto_renew'] = true
        letsencrypt['auto_renew_hour'] = "03"
        letsencrypt['auto_renew_minute'] = "00"
        letsencrypt['auto_renew_day_of_month'] = "*/1"

        nginx['client_max_body_size'] = '250m'
        nginx['redirect_http_to_https'] = true

    cpu_shares: 1024
    mem_limit: '8g'

    volumes:
        - '${GITLAB_VOLUME}/${GITLAB_VERSION}/config:/etc/gitlab'
        - '${GITLAB_VOLUME}/${GITLAB_VERSION}/data:/var/opt/gitlab'
        - '${SSL}/etc/letsencrypt:/etc/gitlab/ssl/letsencrypt'
#       needed for entrypoint to access GITLAB_VOLUME
        - '${GITLAB_VOLUME}/:${GITLAB_VOLUME}'
    logging:
      driver: 'json-file'
      options:
        labels: 'GITLAB/{{.ImageName}}/{{.Name}}/{{.ID}}'
